# Generated by Django 4.2.7 on 2023-12-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booklist",
            name="img",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
