# Generated by Django 4.2.7 on 2023-12-19 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_booklist_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("page", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "BookList_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.booklist",
                    ),
                ),
            ],
        ),
    ]
