# Generated by Django 4.2.7 on 2023-12-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_users_created_at_useraudiolist_aiaudiolist"),
    ]

    operations = [
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Post_id", models.IntegerField()),
                ("User_id", models.CharField(max_length=20)),
                ("content", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Post_id", models.IntegerField()),
                ("media_path", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_id", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
