# Generated by Django 4.2.7 on 2023-12-19 02:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_bookdetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookdetail",
            old_name="BookList_id",
            new_name="BookList",
        ),
    ]
