# Generated by Django 4.2.7 on 2023-12-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_comment_media_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetail",
            name="BookList",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="BookDetail",
                to="product.booklist",
            ),
        ),
    ]
