# Generated by Django 4.2.7 on 2023-12-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_bookdetail_booklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizlist",
            name="BookList",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="QuizList",
                to="product.booklist",
            ),
        ),
        migrations.AlterField(
            model_name="wordlist",
            name="QuizList",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="WordList",
                to="product.quizlist",
            ),
        ),
    ]
