# Generated by Django 4.2.7 on 2023-12-20 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_rename_booklist_id_bookdetail_booklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="booklist",
            old_name="img",
            new_name="img_path",
        ),
        migrations.CreateModel(
            name="WordList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_name", models.CharField(max_length=30)),
                ("img_path", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "QuizList",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.quizlist",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quizlist",
            name="BookList",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.booklist"
            ),
        ),
    ]
