# Generated by Django 4.2.7 on 2023-12-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_quizlist_booklist_alter_wordlist_quizlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiaudiolist",
            name="QuizList",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="AiAudioList",
                to="product.quizlist",
            ),
        ),
        migrations.AlterField(
            model_name="useraudiolist",
            name="QuizList",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserAudioList",
                to="product.quizlist",
            ),
        ),
    ]
