# Generated by Django 4.2.7 on 2023-12-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_aiaudiolist_quizlist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordlist",
            name="QuizList",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="WordList",
                to="product.quizlist",
            ),
        ),
    ]
