# Generated by Django 4.2.7 on 2023-12-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_user_alter_useraudiolist_user_delete_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
