# Generated by Django 4.2.7 on 2023-12-26 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_alter_user_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="Post_id",
        ),
        migrations.RemoveField(
            model_name="media",
            name="Post_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="Post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="product.post",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="media",
            name="Post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Media",
                to="product.post",
            ),
            preserve_default=False,
        ),
    ]
