# Generated by Django 4.2.7 on 2023-12-28 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_remove_comment_post_id_remove_media_post_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="User_id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="User_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="User",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="User",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Post",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
