# Generated by Django 4.2.7 on 2023-12-29 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_remove_comment_user_id_remove_post_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "BookList",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ReadingStatus",
                        to="product.booklist",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ReadingStatus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_right", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "QuizList",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="LearningStatus",
                        to="product.quizlist",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="LearningStatus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
