# Generated by Django 4.2.7 on 2023-12-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_readingstatus_learningstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiaudiolist",
            name="audio_path",
            field=models.FileField(upload_to="audio/"),
        ),
    ]
