# Generated by Django 5.0 on 2024-01-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_alter_aiaudiolist_audio_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="Post",
        ),
        migrations.AlterField(
            model_name="media",
            name="media_path",
            field=models.FileField(upload_to="post/"),
        ),
    ]
