# Generated by Django 4.2.7 on 2024-01-03 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_remove_media_post_alter_media_media_path"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="readingstatus",
            unique_together={("User", "BookList")},
        ),
    ]
