# Generated by Django 4.2.7 on 2023-12-19 01:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookList",
        ),
    ]
